#!/bin/bash

exit_if_errors () {
    error_code=$?
    test "$error_code" -eq 0 || exit "$error_code"
}

cargo clean

export CARGO_INCREMENTAL=0

cargo +nightly rustc -- --test -C link-dead-code -Z profile -C panic=abort -Z panic_abort_tests

exit_if_errors

deps_folder='./target/debug/deps/'
prompt_acc=''

read -p 'run the binary in `'"$deps_folder"'` (TAB should autocomplete it)
' -i "$deps_folder" -e prompt_acc

# without this we get less coverage reported sometimes
export RUST_TEST_THREADS = 1

eval "$prompt_acc"

exit_if_errors

mkdir -p ./target/coverage

exit_if_errors

LCOVOPTS="--gcov-tool llvm-gcov --rc lcov_branch_coverage=1"
LCOVOPTS="${LCOVOPTS} --rc lcov_excl_line=assert"
lcov ${LCOVOPTS} --capture --directory . --base-directory . \
  -o target/coverage/raw.lcov
lcov ${LCOVOPTS} --extract target/coverage/raw.lcov "$(pwd)/*" \
  -o target/coverage/raw_crate.lcov

exit_if_errors

genhtml --branch-coverage --demangle-cpp --legend \
  -o coverage/ \
  target/coverage/raw_crate.lcov




